### ISSUE TITLE
question

### ISSUE THREAD

**Issue by cordoval** [Visithor/visithor#1]
so this package visits a set of given urls

what for? are you crawling stuff? how it is used and what the purpose is, thanks!

**Comment by mmoreram** [comment]
Just for testing. Yes, you can do it with Behat... but behat should be always `given/when/then` and this is much simpler.

**Comment by cordoval** [comment]
I think what i mean here is plain mink, not even behat.

**Comment by mmoreram** [comment]
Yes, but think about the interface for the final user... not easy :(
