### ISSUE TITLE
HTTP verbs?

### ISSUE THREAD

**Issue by nilportugues** [Visithor/visithor#2]
I'm thinking this can be really useful to test API resources. 

How about setting the methods as a third param maybe, just after the status code?

**Comment by mmoreram** [comment]
@nilopc I though about that.

Third parameter will be the verb (GET by default) and the fourth an array of configurations (for ROLE in the case of the Bundle).

What I ask to myself is... does it make sense to add another verb? Would you test a POST/PUT/DELETE route?

**Comment by nilportugues** [comment]
Restful API could benefit of verbs..

**Comment by mmoreram** [comment]
Hmm, true...

**Comment by mmoreram** [comment]
Closed by https://github.com/Visithor/visithor/pull/4
